apiVersion: v1
kind: Pod
metadata:
  name: check-volume-pod
spec:
  containers:
  - name: check-container
    image: busybox
    command: ['sh', '-c', 'sleep 3600']  # Keep the pod running for a while
    volumeMounts:
    - name: shared-volume
      mountPath: /shared_volume
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-volume-claim
