apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  type: NodePort
  selector:
    app: prediction
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 50001
