apiVersion: v1
kind: Service
metadata:
  name: training-service
spec:
  type: NodePort
  selector:
    app: training
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 50002
